# Generated by Django 5.2.1 on 2025-07-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('duracion_horas', models.PositiveSmallIntegerField(help_text='Duración en horas')),
                ('profesor', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=12)),
                ('lugar', models.CharField(choices=[('1', 'Jardín Botánico'), ('2', 'Playa El Encanto'), ('3', 'Biblioteca Municipal'), ('4', 'Centro Cultural Villa Verde'), ('5', 'Gimnasio Municipal'), ('6', 'Sede Junta Vecinal N°5'), ('7', 'Sede Junta Vecinal N°12'), ('8', 'Parque Comunal'), ('9', 'Salón Multiuso Municipal'), ('10', 'Escuela Básica Villa Verde')], max_length=2)),
                ('categoria', models.CharField(choices=[('1', 'Aire Libre'), ('2', 'Arte'), ('3', 'Música'), ('4', 'Salud'), ('5', 'Tecnología'), ('6', 'Oficios'), ('7', 'Educación'), ('8', 'Medioambiente'), ('9', 'Comunidad y Liderazgo'), ('10', 'Recreación')], max_length=2)),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'ordering': ['fecha', 'lugar'],
            },
        ),
    ]
