# Generated by Django 5.1.2 on 2025-07-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taller',
            old_name='duracion_horas',
            new_name='duracion',
        ),
    ]
