# Generated by Django 5.1.2 on 2025-07-06 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_duracion_horas_taller_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
