# Generated by Django 5.1.2 on 2025-07-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taller_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
