# Generated by Django 5.1.2 on 2025-07-06 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
